# Creates the release signing keystore and the properties file Gradle reads.
#
#   powershell -File tools\make-keystore.ps1
#   powershell -File tools\make-keystore.ps1 -Alias anime-release -StoreFile android\keystores\anime-release.jks
#
# Runs on Windows PowerShell 5.1 as well as PowerShell 7.
#
# The keystore is NOT committed (see .gitignore). Losing it means you can never
# update the app on RuStore under the same listing, so back it up somewhere the
# repository is not.

param(
    [string]$StoreFile = "android\keystores\anime-release.jks",
    [string]$Alias = "anime",
    [string]$StorePass = "",
    [string]$KeyPass = "",
    # Validity must comfortably exceed the app's expected lifetime: RuStore
    # refuses an update signed with an expired key, and the key cannot be
    # rotated for an existing listing.
    [int]$ValidityDays = 10950,   # 30 years
    [string]$ApiBaseUrl = "https://anime.teivrim.ru/"
)

$ErrorActionPreference = "Stop"

# keytool ships with the JDK but is not always on PATH.
$keytool = Get-Command keytool -ErrorAction SilentlyContinue
if ($keytool) {
    $keytoolPath = $keytool.Source
} else {
    $candidates = @(
        "$env:JAVA_HOME\bin\keytool.exe",
        "D:\123\jbr\bin\keytool.exe",
        "C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe"
    )
    $keytoolPath = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $keytoolPath) {
        throw "keytool not found. Set JAVA_HOME or put it on PATH."
    }
}

# `ConvertFrom-SecureString -AsPlainText` only exists on PowerShell 7, and this
# script also has to run on the 5.1 that ships with Windows.
function Read-Secret([string]$prompt) {
    $secure = Read-Host $prompt -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        # Clear the unmanaged copy; it would otherwise outlive the process on
        # a crash dump.
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

if ([string]::IsNullOrEmpty($StorePass)) { $StorePass = Read-Secret "Keystore password" }
if ([string]::IsNullOrEmpty($KeyPass)) {
    # A distinct key password is optional in the PKCS12 format; reuse the store
    # password so there is one secret to remember.
    $KeyPass = $StorePass
}

$full = Join-Path (Get-Location) $StoreFile
$dir = Split-Path $full -Parent
if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

if (Test-Path $full) {
    Write-Host "Keystore already exists: $full"
    Write-Host "Delete it first if you really want to generate a new one; the"
    Write-Host "existing one is what RuStore will accept for future updates."
} else {
    & $keytoolPath -genkeypair `
        -alias $Alias `
        -keyalg RSA `
        -keysize 4096 `
        -sigalg SHA256withRSA `
        -validity $ValidityDays `
        -keystore $full `
        -storetype PKCS12 `
        -storepass $StorePass `
        -keypass $KeyPass `
        -dname "CN=Anime Catalog, OU=Teivrim, O=TeivrimOriginal, L=, ST=, C=RU"
    if ($LASTEXITCODE -ne 0) { throw "keytool failed with exit code $LASTEXITCODE" }
    Write-Host "Created $full"
}

$props = @"
# Generated by tools/make-keystore.ps1. Never commit this file.
storeFile=$($full -replace '\\','/')
storePassword=$StorePass
keyAlias=$Alias
keyPassword=$KeyPass
apiBaseUrl=$ApiBaseUrl
"@
$propsPath = Join-Path $dir "keystore.properties"
# `Out-File -Encoding utf8` writes a BOM on 5.1, and java.util.Properties.load
# does not strip one - the first key would come out as "<BOM>storeFile" and the
# build would silently fall back to an unsigned bundle.
[System.IO.File]::WriteAllText($propsPath, $props, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Wrote $propsPath"

Write-Host ""
Write-Host "Certificates:"
& $keytoolPath -list -v -keystore $full -storepass $StorePass 2>&1 |
    Select-String -Pattern "Alias name|Valid from|SHA256" | Select-Object -First 6
